apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp_container
    image: busybox
    command: ['sh', '-c', 'echo Hello DK && sleep 3600']
